### ISSUE TITLE
Feature Request | Port knocking для ssh (для начала)

### ISSUE THREAD

**Issue by x09** [MyConnector/MyConnector#17]
Предлагаю добавить, по аналогии, как в putty механизм port knocking. Когда клиент сначала стукается в определенной последовательности по указаным портам(tcp/udp), затем открывается само соединение.

Оформить можно в виде одной строки типа 
`tcp:4440 tcp:1111 udp:8899`
т.е. один пакет по tcp на порт 4440, один по tcp на 1111 и один по udp на 8899, лишь затем инициализация соединения..

**Comment by ekorneechev** [comment]
Клиент 'knock' в Альте работает?

**Comment by ekorneechev** [comment]
@x09, нужно протестировать из ветки [ssh_knocking](https://github.com/MyConnector/MyConnector/tree/ssh_knocking) - на Альте доустановить `knock`

У меня он "стучится" и ему открывают как надо, но Remmina (в отличии от обычного ssh) - не подключается.

**Comment by ekorneechev** [comment]
На производных Ubuntu - клиент в пакете с сервером `knockd`

**Comment by x09** [comment]
knok в альте прекрасно отработал и все работает как надо
