### ISSUE TITLE
Добавить x2go клиента

### ISSUE THREAD

**Issue by x09** [MyConnector/MyConnector#19]
Чтобы закрыть все потребности прогрессивного человечества, прошу рассмотреть возможность добавления протокола x2go.

p.s. https://wiki.x2go.org/doku.php
p.p.s. пример консольного клиента https://wiki.x2go.org/doku.php/doc:usage:pyhoca-cli

**Comment by ekorneechev** [comment]
> Чтобы закрыть все потребности прогрессивного человечества, прошу рассмотреть возможность добавления протокола x2go.

Какой минимум параметров необходим помимо адреса сервера и имени пользователя?

**Comment by x09** [comment]
1. сервер
2. имя пользователя
3. тип сессии (KDE, GNOME, LXDE, LXQt, XFCE, MATE,  UNITY, CINNAMON, TRINITY, OPENBOX, ICEWM, XDMCP), именно в таком регистре. Или пользовательская команда
4. порт (22)
5. геометрия окна (-g GEOMETRY)

думаю это самое главное
