### ISSUE TITLE
Вкладки

### ISSUE THREAD

**Issue by petr-akhlamov** [MyConnector/MyConnector#20]
Здравствуйте! Спасибо Вам большое за отличный клиент.
Можно, пожалуйста, как будет время и возможность сделать вкладки активных подключений наподобие mRemoteNG? Перехожу сейчас на предприятии с Windows на Linux, привык к такой фишке, Remmina тупит, а Ваш клиент отлично работает. Единственное, такой фичи нет.

**Comment by ekorneechev** [comment]
Речь про это?
![remmina](https://user-images.githubusercontent.com/11332930/115348477-56abfb80-a1bb-11eb-89dc-b0ab88fbe77b.png)

**Comment by petr-akhlamov** [comment]
Да.

**Comment by ekorneechev** [comment]
Мой клиент только запускает другие программы с указанными параметрами, в том числе и Remmina.
Во FreeRDP такой функциональности например пока нет. Собирать же окна разных программ в одно окно MyConnector - "картинка в картинке" - нетривиальная задача.
