### ISSUE TITLE
Не открываются дополнительные параметры при выборе RDP

### ISSUE THREAD

**Issue by nargamard** [MyConnector/MyConnector#21]
Не открываются дополнительные параметры при выборе RDP. Не подключается по RDP по ранее настроенным подключениям.Так происходит при выборе в параметрах freerdp. Если выбрать remmina, то работает нормально. При этом подключиться xfreerdp через консоль удаётся.

**Comment by ekorneechev** [comment]
Запустите в консоли и приложите вывод ошибок.

**Comment by ekorneechev** [comment]
cbc9c8cce - обновлена проверка ошибок FreeRDP
