### ISSUE TITLE
Невозможно подключиться по RDP если в пароле присутствуют некоторые специальные символы

### ISSUE THREAD

**Issue by Saintscream** [MyConnector/MyConnector#27]
При подключении по протоколу RDP через MyConnector заметил, что не все пароли могут приниматься программой.
Например, если пароль учетной записи содержит символ ';' или '~' -  то подключиться не получается. Возможно есть еще какие-либо символы, которые не принимаются. Через xfreerdp с этим же паролем подключиться получается.

**Comment by ekorneechev** [comment]
Исправлено в a82d07309
