### ISSUE TITLE
Перетаскивание программы в оконном режиме

### ISSUE THREAD

**Issue by Saintscream** [MyConnector/MyConnector#28]
При переключении программы с полноэкранного режима в оконный и при дальнейшей попытки переместить данное окно в любую часть экрана, программа сворачивается в панель задач и её не получается развернуть. Помогает только нажатие пкм и выбор там полноэкранного режима. Наблюдается на всех редакциях Альт Рабочая станция К 10.X

**Comment by ekorneechev** [comment]
На Альт РС К 10.2 не воспроизводится. Или ЧЯДНТ (см.видео)?

https://github.com/MyConnector/MyConnector/assets/11332930/efbc7e7a-ef59-403f-92f6-98bffffa8713

**Comment by Saintscream** [comment]
Воспроизводится. Нужно подключиться по rdp на весь экран. Далее перейти не в полный экран и попробовать перетянуть окно в любое местоОтправлено с телефона-------- Исходное сообщение --------От: Korneechev Evgeniy ***@***.***>Дата: пн, 20 нояб. 2023 г., 15:21Кому: MyConnector/MyConnector ***@***.***>Копия: Saintscream ***@***.***>, Author ***@***.***>Тема: Re: [MyConnector/MyConnector] Перетаскивание программы в оконном режиме (Issue #28)
На Альт РС К 10.2 не воспроизводится. Или ЧЯДНТ (см.видео)?
https://github.com/MyConnector/MyConnector/assets/11332930/efbc7e7a-ef59-403f-92f6-98bffffa8713

**Comment by ekorneechev** [comment]
Видимо проблемы xfreerdp в Plasma (KDE), не ошибка MyConnector.
